require("jaimedgp.core.options")
require("jaimedgp.lazy")
require("jaimedgp.core.diagnostic")
require("jaimedgp.core.autocmd")
require("jaimedgp.core.icons")
require("jaimedgp.core.keymaps")
require("jaimedgp.core.options")
require("jaimedgp.snippets")

vim.cmd.colorscheme("gruvbox")
